<?php

declare(strict_types=1);

namespace Plugin\Landswitcher\Model;

use Exception;
use JTL\Model\DataAttribute;
use JTL\Model\DataModel;

/**
 * Class TLandswitcher_redirectsModel
 * This class is generated by shopcli model:create
 *
 * @package Plugin\Landswitcher\Models
 * @property int $redirectID
 * @method int getRedirectID()
 * @method void setRedirectID(int $value)
 * @property string $cISO
 * @method string getCISO()
 * @method void setCISO(string $value)
 * @property string $url
 * @method string getUrl()
 * @method void setUrl(string $value)
 */
final class TLandswitcherRedirectsModel extends DataModel
{
    /**
     * @inheritdoc
     */
    public function getTableName(): string
    {
        return 'landswitcher_redirects';
    }

    /**
     * Setting of keyname is not supported!
     * Call will always throw an Exception with code ERR_DATABASE!
     * @inheritdoc
     */
    public function setKeyName($keyName): void
    {
        throw new Exception(__METHOD__ . ': setting of keyname is not supported', self::ERR_DATABASE);
    }

    /**
     * @inheritdoc
     */
    protected function onRegisterHandlers(): void
    {
        parent::onRegisterHandlers();
    }

    /**
     * @inheritdoc
     */
    public function getAttributes(): array
    {
        static $attributes = null;
        if ($attributes === null) {
            $attributes   = [];
            $attributes['redirectID'] = DataAttribute::create('redirectID', 'int', null, false, true);
            $attributes['cISO'] = DataAttribute::create('cISO', 'varchar', null, false, false);
            $attributes['url'] = DataAttribute::create('url', 'varchar', null, false, false);
        }

        return $attributes;
    }
}
